name: Branch Check

on:
  pull_request:
      branches: [ master, dev, release/** ]

jobs:
  checker-job2:
    runs-on: ubuntu-latest
    steps:
      - name: branch-check
        run: echo ${{ github.base_ref }}
      - if: ${{ startsWith(github.event.pull_request.base.ref, 'master') && !startsWith(github.head_ref, 'release/') }}
        run: exit 1

