name: Branch Check

on:
  pull_request:

jobs:
  checker-job:
    runs-on: ubuntu-latest
    steps:
      - name: branch-check
        run: echo ${{ github.head_ref }}
      - if: "!startsWith(github.head_ref, 'release/')"
        run: exit 1
