name: Branch Checker2

on:
  pull_request:

jobs:
  checker-job:
    runs-on: ubuntu-latest
    steps:
      - name: branch
      - if: "!startsWith(github.base_ref, 'release/')"
        run: |
          echo ${{ github.head_ref }}
          echo ${{ github.base_ref }}
          echo ${{ github.ref }}
          exit 1
