name: Branch Checker

on:
    pull_request:
      branches: [ dev ]

jobs:
  checker-job:
    runs-on: ubuntu-latest
    steps:
      - name: branch
      - if: "!startsWith(github.ref, 'release/')"
        run: |
          echo ${{ github.head_ref }}
          echo ${{ github.base_ref }}
          echo ${{ github.ref }}
          exit 1
