name: Branch Check

on:
  pull_request:
      branches: [ master, dev, release/** ]

jobs:
  checker-job:
    runs-on: ubuntu-latest
    steps:
      - name: branch-check
        run: echo ${{ github.head_ref }}
      - if: ${{ startsWith(github.base_ref, 'master') }}
        run: echo ${{ github.base_ref }}
      - if: "startsWith(github.base_ref, 'master') && startsWith(github.head_ref, 'release/')"
        run: exit 1
