name: "Pull Request Labeler"
on:
  pull_request:
    types: [opened]
    branches:
      - release/*

jobs:
  triage:
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
    - uses: TimonVS/pr-labeler-action@v3
      with:
        repo-token: "${{ secrets.GITHUB_TOKEN }}"
