name: "Pull Request Labeler"
on:
  push:
    branches:
      - 'releases/**'

jobs:
  auto-labeler:
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
    - uses: actions/labeler@v4
      with:
        repo-token: "${{ secrets.GITHUB_TOKEN }}"
