name: "Pull Request Labeler"
on:
  pull_request:
    types: [opened]
    branches:
      - release/*

jobs:
  triage:
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
    - uses: TimonVS/pr-labeler-action@v3
      with:
          configuration-path: .github/labeler.yml # optional, .github/pr-labeler.yml is the default value
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
