name: WIP
on:
  pull_request:
    types: [ opened, synchronize, reopened, edited ]

jobs:
  wip:
    runs-on: ubuntu-latest
    steps:
      - if: ${{ contains(github.event.pull_request.title, 'WIP') }}
        run: exit 1
