name: WIP
on:
  pull_request:
    types: [ opened, synchronize, reopened, edited ]

jobs:
  wip:
    runs-on: ubuntu-latest
    env:
      PULL_REQUEST_TITLE: ${{ github.event.pull_request.title }}
    steps:
      - name: branch-check
      - if: "!contains(github.event.pull_request.title, '[WIP]')"
        run: exit 1


