name: WIP
on:
  pull_request:
    types: [ opened, synchronize, reopened, edited ]

jobs:
  wip:
    runs-on: ubuntu-latest
    env:
      PULL_REQUEST_TITLE: ${{ github.event.pull_request.title }}
    steps:
      - name: branch-check
        run: |
          echo ${{ github.event.pull_request.title }}
          echo $PULL_REQUEST_TITLE
      - if: "!contains($PULL_REQUEST_TITLE, '[WIP]')"
        run: exit 1


